# Generated by Django 4.2.3 on 2023-07-29 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('blog_image', models.ImageField(blank=True, default=None, upload_to='')),
                ('blog_content', models.TextField()),
            ],
        ),
    ]
