# Generated by Django 4.2.3 on 2023-07-31 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_operations', '0003_alter_blogmodel_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='author',
        ),
    ]
